id: P006837
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 12:25:49.559127
source_metadata:
  id: bdr:W1KG13115
  title: རྒྱུད་བཞི། ༼ལྕགས་པོ་རི་པར་མ།༽
  author: ''
  volumes:
    333c0d80194b40a28db0abf0d7852056:
      image_group_id: I1KG13487
      title: ''
      volume_number: 1
      total_pages: 740
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
