id: I4327BCE9
legacy_id: P006837
ocr_import_info:
  bdrc_scan_id: W1KG13115
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T14:10:32'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T03:45:58.766847+00:00'
last_modified: 2022-08-31 11:46:21.710137
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG13115
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG13115
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྒྱུད་བཞི། ༼ལྕགས་པོ་རི་པར་མ།༽
statistics:
  ocr_word_mean_confidence_index: 0.5695014209904316
  ocr_word_median_confidence_index: 0.550000011920929
quality: null
bases:
  I1KG13487:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG13487
      total_pages: 740
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG13487.txt
    statistics:
      ocr_word_median_confidence_index: 0.550000011920929
      ocr_word_mean_confidence_index: 0.5695014209904316
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
